import greenfoot.*;  // (World, Actor, GreenfootImage, Greenfoot and MouseInfo)

/**
 * Write a description of class MyWorld here.
 * 
 * @author (your name) 
 * @version (a version number or a date)
 */
public class MyWorld extends World
{

    /**
     * Constructor for objects of class MyWorld.
     * 
     */
    public MyWorld()
    {    
        // Create a new world with 600x400 cells with a cell size of 1x1 pixels.
        super(800, 600, 1); 
        prepare();
    }
    
    /**
     * Prepare the world for the start of the program.
     * That is: create the initial objects and add them to the world.
     */
    private void prepare()
    {
        WallWidthMedium wallWidthMedium = new WallWidthMedium();
        addObject(wallWidthMedium,67,553);
        WallWidthMedium wallWidthMedium2 = new WallWidthMedium();
        addObject(wallWidthMedium2,178,553);
        WallWidthMedium wallWidthMedium3 = new WallWidthMedium();
        addObject(wallWidthMedium3,320,553);
        WallWidthMedium wallWidthMedium4 = new WallWidthMedium();
        addObject(wallWidthMedium4,497,553);
        WallWidthMedium wallWidthMedium5 = new WallWidthMedium();
        addObject(wallWidthMedium5,417,553);
        WallWidthMedium wallWidthMedium6 = new WallWidthMedium();
        addObject(wallWidthMedium6,645,553);
        WallWidthSmall wallWidthSmall = new WallWidthSmall();
        addObject(wallWidthSmall,698,553);

        WallHeightSmall wallHeightSmall = new WallHeightSmall();
        addObject(wallHeightSmall,735,368);
        WallHeightMedium wallHeightMedium = new WallHeightMedium();
        addObject(wallHeightMedium,735,421);
        WallHeightMedium wallHeightMedium2 = new WallHeightMedium();
        addObject(wallHeightMedium2,735,452);
        WallHeightMedium wallHeightMedium3 = new WallHeightMedium();
        addObject(wallHeightMedium3,735,512);

        WallHeightMedium wallHeightMedium4 = new WallHeightMedium();
        addObject(wallHeightMedium4,734,229);
        WallHeightMedium wallHeightMedium5 = new WallHeightMedium();
        addObject(wallHeightMedium5,734,274);
        WallHeightMedium wallHeightMedium6 = new WallHeightMedium();
        addObject(wallHeightMedium6,734,155);
        WallHeightMedium wallHeightMedium7 = new WallHeightMedium();
        addObject(wallHeightMedium7,734,80);

        WallWidthMedium wallWidthMedium7 = new WallWidthMedium();
        addObject(wallWidthMedium7,666,47);
        WallWidthMedium wallWidthMedium8 = new WallWidthMedium();
        addObject(wallWidthMedium8,530,47);
        WallWidthMedium wallWidthMedium9 = new WallWidthMedium();
        addObject(wallWidthMedium9,407,47);
        WallWidthMedium wallWidthMedium10 = new WallWidthMedium();
        addObject(wallWidthMedium10,248,47);
        wallWidthMedium10.setLocation(256,47);
        WallWidthMedium wallWidthMedium11 = new WallWidthMedium();
        addObject(wallWidthMedium11,326,47);
        WallWidthMedium wallWidthMedium12 = new WallWidthMedium();
        addObject(wallWidthMedium12,117,47);
        wallWidthMedium12.setLocation(125,47);

        WallHeightMedium wallHeightMedium8 = new WallHeightMedium();
        addObject(wallHeightMedium8,55,73);
        WallHeightMedium wallHeightMedium9 = new WallHeightMedium();
        addObject(wallHeightMedium9,55,156);
        wallHeightMedium8.setLocation(55,92);
        WallHeightMedium wallHeightMedium10 = new WallHeightMedium();
        addObject(wallHeightMedium10,55,231);
        WallHeightMedium wallHeightMedium11 = new WallHeightMedium();
        addObject(wallHeightMedium11,55,306);
        WallHeightMedium wallHeightMedium12 = new WallHeightMedium();
        addObject(wallHeightMedium12,55,377);
        WallHeightMedium wallHeightMedium13 = new WallHeightMedium();
        addObject(wallHeightMedium13,55,464);
        wallHeightMedium13.setLocation(55,440);
        WallHeightMedium wallHeightMedium14 = new WallHeightMedium();
        addObject(wallHeightMedium14,55,466);
        WallWidthMedium wallWidthMedium13 = new WallWidthMedium();
        addObject(wallWidthMedium13,201,450);
        wallWidthMedium13.setLocation(189,450);
        WallWidthMedium wallWidthMedium14 = new WallWidthMedium();
        addObject(wallWidthMedium14,317,451);
        WallWidthSmall wallWidthSmall2 = new WallWidthSmall();
        addObject(wallWidthSmall2,89,502);
        wallWidthSmall2.setLocation(95,494);
        WallHeightSmall wallHeightSmall2 = new WallHeightSmall();
        addObject(wallHeightSmall2,121,466);
        wallHeightSmall2.setLocation(130,473);
        wallWidthMedium13.setLocation(180,447);
        wallWidthMedium13.setLocation(197,451);
        WallHeightSmall wallHeightSmall3 = new WallHeightSmall();
        addObject(wallHeightSmall3,187,540);
        wallHeightSmall3.setLocation(190,523);
        WallWidthSmall wallWidthSmall3 = new WallWidthSmall();
        addObject(wallWidthSmall3,220,503);
        wallWidthSmall3.setLocation(225,503);
        WallHeightSmall wallHeightSmall4 = new WallHeightSmall();
        addObject(wallHeightSmall4,326,530);
        wallHeightSmall4.setLocation(326,525);
        WallHeightMedium wallHeightMedium15 = new WallHeightMedium();
        addObject(wallHeightMedium15,461,500);
        wallHeightMedium15.setLocation(460,518);
        WallHeightMedium wallHeightMedium16 = new WallHeightMedium();
        addObject(wallHeightMedium16,457,480);
        wallHeightMedium15.setLocation(459,488);
        WallWidthMedium wallWidthMedium15 = new WallWidthMedium();
        addObject(wallWidthMedium15,661,500);
        wallWidthMedium15.setLocation(596,499);
        WallWidthMedium wallWidthMedium16 = new WallWidthMedium();
        addObject(wallWidthMedium16,596,499);
        WallHeightMedium wallHeightMedium17 = new WallHeightMedium();
        addObject(wallHeightMedium17,529,455);
        wallHeightMedium17.setLocation(528,427);
        WallHeightSmall wallHeightSmall5 = new WallHeightSmall();
        addObject(wallHeightSmall5,528,427);
        wallHeightMedium17.setLocation(530,423);
        WallWidthSmall wallWidthSmall4 = new WallWidthSmall();
        addObject(wallWidthSmall4,500,400);
        wallWidthSmall4.setLocation(497,399);
        wallWidthSmall4.setLocation(494,405);
        wallWidthSmall4.setLocation(478,399);
        wallWidthSmall4.setLocation(491,397);
        WallWidthMedium wallWidthMedium17 = new WallWidthMedium();
        addObject(wallWidthMedium17,612,300);
        wallWidthMedium17.setLocation(597,300);
        wallWidthMedium17.setLocation(536,297);
        WallWidthMedium wallWidthMedium18 = new WallWidthMedium();
        addObject(wallWidthMedium18,536,297);
        wallWidthMedium17.setLocation(532,300);
        WallWidthSmall wallWidthSmall5 = new WallWidthSmall();
        addObject(wallWidthSmall5,425,352);
        WallHeightMedium wallHeightMedium18 = new WallHeightMedium();
        addObject(wallHeightMedium18,390,399);
        wallHeightMedium18.setLocation(382,388);
        wallHeightMedium18.setLocation(390,369);
        wallHeightMedium18.setLocation(385,380);
        wallHeightMedium18.setLocation(384,399);
        WallHeightMedium wallHeightMedium19 = new WallHeightMedium();
        addObject(wallHeightMedium19,384,399);
        wallHeightMedium18.setLocation(386,412);
        WallHeightSmall wallHeightSmall6 = new WallHeightSmall();
        addObject(wallHeightSmall6,460,322);
        wallHeightSmall6.setLocation(460,318);
        wallHeightSmall6.setLocation(463,322);
        WallWidthMedium wallWidthMedium19 = new WallWidthMedium();
        addObject(wallWidthMedium19,120,399);
        wallWidthMedium19.setLocation(123,399);
        WallWidthSmall wallWidthSmall6 = new WallWidthSmall();
        addObject(wallWidthSmall6,290,402);
        wallWidthSmall6.setLocation(150,351);
        wallWidthSmall6.setLocation(151,343);
        wallWidthSmall6.setLocation(792,307);
        WallWidthMedium wallWidthMedium20 = new WallWidthMedium();
        addObject(wallWidthMedium20,179,350);
        wallWidthMedium20.setLocation(196,349);
        wallWidthSmall6.setLocation(270,343);
        wallWidthSmall6.setLocation(302,346);
        wallWidthSmall6.setLocation(286,347);
        WallHeightSmall wallHeightSmall7 = new WallHeightSmall();
        addObject(wallHeightSmall7,325,369);
        WallWidthSmall wallWidthSmall7 = new WallWidthSmall();
        addObject(wallWidthSmall7,285,395);
        wallWidthSmall7.setLocation(296,396);
        WallHeightSmall wallHeightSmall8 = new WallHeightSmall();
        addObject(wallHeightSmall8,120,321);
        wallHeightSmall8.setLocation(126,321);
        WallWidthSmall wallWidthSmall8 = new WallWidthSmall();
        addObject(wallWidthSmall8,89,301);
        wallWidthSmall8.setLocation(91,301);
        WallWidthMedium wallWidthMedium21 = new WallWidthMedium();
        addObject(wallWidthMedium21,258,299);
        WallWidthSmall wallWidthSmall9 = new WallWidthSmall();
        addObject(wallWidthSmall9,352,295);
        wallWidthSmall9.setLocation(352,299);
        WallHeightSmall wallHeightSmall9 = new WallHeightSmall();
        addObject(wallHeightSmall9,393,272);
        WallHeightSmall wallHeightSmall10 = new WallHeightSmall();
        addObject(wallHeightSmall10,415,253);
        wallHeightSmall10.setLocation(458,172);
        WallWidthSmall wallWidthSmall10 = new WallWidthSmall();
        addObject(wallWidthSmall10,425,245);
        wallWidthSmall10.setLocation(434,247);
        WallHeightMedium wallHeightMedium20 = new WallHeightMedium();
        addObject(wallHeightMedium20,528,263);
        WallHeightMedium wallHeightMedium21 = new WallHeightMedium();
        addObject(wallHeightMedium21,526,187);
        wallHeightMedium21.setLocation(528,188);
        WallWidthMedium wallWidthMedium22 = new WallWidthMedium();
        addObject(wallWidthMedium22,452,146);
        wallWidthMedium22.setLocation(467,153);
        wallWidthMedium22.setLocation(459,150);
        WallWidthSmall wallWidthSmall11 = new WallWidthSmall();
        addObject(wallWidthSmall11,371,150);
        WallHeightSmall wallHeightSmall11 = new WallHeightSmall();
        addObject(wallHeightSmall11,328,126);
        WallWidthMedium wallWidthMedium23 = new WallWidthMedium();
        addObject(wallWidthMedium23,455,98);
        WallHeightSmall wallHeightSmall12 = new WallHeightSmall();
        addObject(wallHeightSmall12,664,327);
        WallWidthMedium wallWidthMedium24 = new WallWidthMedium();
        addObject(wallWidthMedium24,656,401);
        WallHeightSmall wallHeightSmall13 = new WallHeightSmall();
        addObject(wallHeightSmall13,587,369);
        wallHeightSmall13.setLocation(592,369);
        wallHeightSmall13.setLocation(588,373);
        WallHeightSmall wallHeightSmall14 = new WallHeightSmall();
        addObject(wallHeightSmall14,528,331);
        wallHeightSmall14.setLocation(530,323);
        WallHeightSmall wallHeightSmall15 = new WallHeightSmall();
        addObject(wallHeightSmall15,386,477);
        WallHeightSmall wallHeightSmall16 = new WallHeightSmall();
        addObject(wallHeightSmall16,588,430);
        WallHeightSmall wallHeightSmall17 = new WallHeightSmall();
        addObject(wallHeightSmall17,319,225);
        wallHeightSmall17.setLocation(333,230);
        WallWidthSmall wallWidthSmall12 = new WallWidthSmall();
        addObject(wallWidthSmall12,624,445);
        WallWidthSmall wallWidthSmall13 = new WallWidthSmall();
        addObject(wallWidthSmall13,624,253);
        wallWidthSmall13.setLocation(664,249);
        WallHeightMedium wallHeightMedium22 = new WallHeightMedium();
        addObject(wallHeightMedium22,664,249);
        wallWidthSmall13.setLocation(664,258);
        WallHeightMedium wallHeightMedium23 = new WallHeightMedium();
        addObject(wallHeightMedium23,662,172);
        wallHeightMedium23.setLocation(666,188);
        WallHeightMedium wallHeightMedium24 = new WallHeightMedium();
        addObject(wallHeightMedium24,663,117);
        wallHeightMedium24.setLocation(666,139);
        WallHeightMedium wallHeightMedium25 = new WallHeightMedium();
        addObject(wallHeightMedium25,592,95);
        wallHeightMedium25.setLocation(594,90);
        WallHeightMedium wallHeightMedium26 = new WallHeightMedium();
        addObject(wallHeightMedium26,595,168);
        wallHeightMedium26.setLocation(588,153);
        wallHeightMedium26.setLocation(592,163);
        WallWidthSmall wallWidthSmall14 = new WallWidthSmall();
        addObject(wallWidthSmall14,558,100);
        wallWidthSmall14.setLocation(559,98);
        WallWidthSmall wallWidthSmall15 = new WallWidthSmall();
        addObject(wallWidthSmall15,142,102);
        wallWidthSmall15.setLocation(148,102);
        WallWidthMedium wallWidthMedium25 = new WallWidthMedium();
        addObject(wallWidthMedium25,117,150);
        wallWidthMedium25.setLocation(122,150);
        WallHeightSmall wallHeightSmall18 = new WallHeightSmall();
        addObject(wallHeightSmall18,190,121);
        wallHeightSmall18.setLocation(184,120);
        WallWidthMedium wallWidthMedium26 = new WallWidthMedium();
        addObject(wallWidthMedium26,325,202);
        wallWidthMedium26.setLocation(318,200);
        WallWidthSmall wallWidthSmall16 = new WallWidthSmall();
        addObject(wallWidthSmall16,240,200);
        wallWidthSmall16.setLocation(226,196);
        wallWidthSmall16.setLocation(226,200);
        WallHeightMedium wallHeightMedium27 = new WallHeightMedium();
        addObject(wallHeightMedium27,256,87);
        WallHeightMedium wallHeightMedium28 = new WallHeightMedium();
        addObject(wallHeightMedium28,258,156);
        wallHeightMedium28.setLocation(255,156);
        WallHeightMedium wallHeightMedium29 = new WallHeightMedium();
        addObject(wallHeightMedium29,120,197);
        wallHeightMedium29.setLocation(121,192);
        WallHeightSmall wallHeightSmall19 = new WallHeightSmall();
        addObject(wallHeightSmall19,119,243);
        wallHeightSmall19.setLocation(122,235);
        WallWidthMedium wallWidthMedium27 = new WallWidthMedium();
        addObject(wallWidthMedium27,194,246);
        wallWidthMedium27.setLocation(188,252);
        WallHeightSmall wallHeightSmall20 = new WallHeightSmall();
        addObject(wallHeightSmall20,260,276);
        wallHeightSmall20.setLocation(253,270);
        wallWidthSmall13.setLocation(664,271);
        wallWidthSmall13.setLocation(665,243);
        wallHeightSmall12.setLocation(659,313);
        wallWidthSmall13.setLocation(647,295);
        wallWidthSmall13.setLocation(636,301);
        wallHeightSmall12.setLocation(664,337);
        wallHeightMedium22.setLocation(663,267);
        wallHeightMedium22.setLocation(669,259);
        wallHeightSmall12.setLocation(662,311);
        wallWidthMedium15.setLocation(658,496);
        wallHeightMedium17.setLocation(526,470);
        wallHeightSmall12.setLocation(662,336);
        wallHeightSmall12.setLocation(666,321);
        wallHeightMedium15.setLocation(458,538);
        wallHeightMedium15.setLocation(458,515);
        Mouse mouse = new Mouse();
        addObject(mouse,100,516);
        mouse.setLocation(65,528);
        WallWidthMedium wallWidthMedium28 = new WallWidthMedium();
        addObject(wallWidthMedium28,38,492);
        Cheese cheese = new Cheese();
        addObject(cheese,694,524);
        Cheese cheese2 = new Cheese();
        addObject(cheese2,142,124);
        Cheese cheese3 = new Cheese();
        addObject(cheese3,548,73);
        Cheese cheese4 = new Cheese();
        addObject(cheese4,91,459);
        Enemy enemy = new Enemy();
        addObject(enemy,216,528);
        Enemy enemy2 = new Enemy();
        addObject(enemy2,279,75);
        Enemy enemy3 = new Enemy();
        addObject(enemy3,614,67);
        enemy3.setLocation(616,71);
        enemy3.setLocation(711,71);
        Enemy enemy4 = new Enemy();
        addObject(enemy4,89,182);
        Goal goal = new Goal();
        addObject(goal,748,326);
        goal.setLocation(755,323);
        goal.setLocation(755,325);
        goal.setLocation(751,325);
        goal.setLocation(749,331);
        goal.setLocation(782,325);
        goal.setLocation(778,331);
    }
}
